version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./app
    command: gunicorn -w 4 -b 0.0.0.0 'flask_server:create_app()'
  apache:
    container_name: apache
    restart: always
    build: ./apache
    ports:
      - "443:443"
    depends_on:
      - flask_app